In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Carregar os datasets
df_train = pd.read_csv(f'challenge-webmedia-e-globo-2023/files/treino/treino_parte1.csv')
df_items = pd.read_csv(f'challenge-webmedia-e-globo-2023/itens/itens/itens-parte1.csv')

In [2]:
df_train.head()

,userId,userType,historySize,history,timestampHistory,numberOfClicksHistory,timeOnPageHistory,scrollPercentageHistory,pageVisitsCountHistory,timestampHistory_new
0,f98d1132f60d46883ce49583257104d15ce723b3bbda21...,Non-Logged,3,"c8aab885-433d-4e46-8066-479f40ba7fb2, 68d2039c...","1657146417045, 1657146605778, 1657146698738","76, 38, 41","20380, 21184, 35438","50.3, 18.18, 16.46","2, 1, 1","1657146417045, 1657146605778, 1657146698738"
1,2c1080975e257ed630e26679edbe4d5c850c65f3e09f65...,Non-Logged,60,"3325b5a1-979a-4cb3-82b6-63905c9edbe8, fe856057...","1656684240278, 1656761266729, 1656761528085, 1...","7, 80, 2, 1, 7, 62, 26, 44, 4, 4, 14, 45, 13, ...","6049, 210489, 8672, 10000, 30000, 123007, 9965...","25.35, 45.66, 35.3, 28.05, 36.53, 47.57, 55.33...","1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1...","1656684240278, 1656761266729, 1656761528085, 1..."
2,0adffd7450d3b9840d8c6215f0569ad942e782fb19b805...,Logged,107,"04756569-593e-4133-a95a-83d35d43dbbd, 29b6b142...","1656678946256, 1656701076495, 1656701882565, 1...","0, 0, 0, 0, 0, 44, 0, 0, 2, 1, 0, 0, 0, 44, 0,...","311274, 140000, 32515, 157018, 118689, 159243,...","67.58, 47.22, 41.52, 63.09, 51.38, 65.11, 71.9...","1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1...","1656678946256, 1656701076495, 1656701882565, 1..."
3,c1e8d644329a78ea1f994292db624c57980b2886cfbc2d...,Non-Logged,56,"1f2b9c2f-a2d2-4192-b009-09065da8ec23, 04756569...","1658333312180, 1658404553818, 1658408449062, 1...","8, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 1...","182696, 91925, 30000, 273655, 126409, 42980, 1...","58.26, 72.66, 22.57, 59.89, 40.36, 36.35, 14.7...","1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","1658333312180, 1658404553818, 1658408449062, 1..."
4,e777d1f31d4d955b63d60acc13df336d3903f52ab8f8f4...,Non-Logged,4,"bebdeb3e-1699-43e0-a1b8-989f5a6ab679, f4b484a7...","1658766608801, 1658766608801, 1660084035094, 1...","579, 579, 7, 2","801396, 801396, 10000, 10000","78.74, 78.74, 16.71, 9.34","7, 7, 1, 1","1658766608801, 1658766608801, 1660084035094, 1..."

In [3]:
df_items.head()

,page,url,issued,modified,title,body,caption
0,13db0ab1-eea2-4603-84c4-f40a876c7400,http://g1.globo.com/am/amazonas/noticia/2022/0...,2022-06-18 20:37:45+00:00,2023-04-15 00:02:08+00:00,Caso Bruno e Dom: 3º suspeito tem prisão tempo...,"Após audiência de custódia, a Justiça do Amazo...",Jeferson da Silva Lima foi escoltado por agent...
1,92907b73-5cd3-4184-8d8c-e206aed2bf1c,http://g1.globo.com/pa/santarem-regiao/noticia...,2019-06-20 17:19:52+00:00,2023-06-16 20:19:15+00:00,Linguajar dos santarenos é diferenciado e chei...,Vista aérea de Santarém\nÁdrio Denner/ AD Prod...,As expressões santarenas não significam apenas...
2,61e07f64-cddf-46f2-b50c-ea0a39c22050,http://g1.globo.com/mundo/noticia/2022/07/08/e...,2022-07-08 08:55:52+00:00,2023-04-15 04:25:39+00:00,Ex-premiê Shinzo Abe morre após ser baleado no...,Novo vídeo mostra que assassino de Shinzo Abe ...,Ex-primeiro-ministro foi atingido por tiros de...
3,30e2e6c5-554a-48ed-a35f-6c6691c8ac9b,http://g1.globo.com/politica/noticia/2021/09/0...,2021-09-09 19:06:46+00:00,2023-06-07 17:44:54+00:00,"Relator no STF, Fachin vota contra marco tempo...","Relator no STF, Fachin vota contra marco tempo...",Ministro defendeu que posse indígena é diferen...
4,9dff71eb-b681-40c7-ac8d-68017ac36675,http://g1.globo.com/politica/noticia/2021/09/1...,2021-09-15 19:16:13+00:00,2023-06-07 17:43:39+00:00,"\nApós 2 votos, pedido de vista suspende julga...",Após um pedido de vista (mais tempo para análi...,"Pelo marco temporal, índios só podem reivindic..."

In [4]:
df_train["history"][0].split(", ")

['c8aab885-433d-4e46-8066-479f40ba7fb2',
 '68d2039c-c9aa-456c-ac33-9b2e8677fba7',
 '13e423ce-1d69-4c78-bc18-e8c8f7271964']

In [5]:
teste = df_train["history"].str.split(", ")
teste.explode().value_counts()

history
d2593c3d-2347-40d9-948c-b6065e8459a9    4282
f6b5d170-48b9-4f8e-88d4-c84b6668f3bd    3873
1f32787b-de2b-49be-8c20-ddaeae34cc22    3395
f0a78e58-ec7e-494c-9462-fbd6446a9a89    3192
6a83890a-d9e9-4f6b-a6c6-90d031785bbf    3121
                                        ...
22c36dd5-ef5e-4326-948e-b2fe7d10ed26       1
286b2ad0-dfa6-496f-a9ae-f773b9782427       1
3137dbaf-d683-44b1-b512-222287710829       1
15fd7d1f-1081-4b22-b50d-b508273607d5       1
b8ced8b2-c82b-42da-bfa9-2ac642127030       1
Name: count, Length: 108573, dtype: int64

In [6]:
# Criar um ranking de popularidade baseado no número de cliques
popular_articles = df_train["history"].str.split(", ").explode().value_counts().index.tolist()
popular_articles

['d2593c3d-2347-40d9-948c-b6065e8459a9',
 'f6b5d170-48b9-4f8e-88d4-c84b6668f3bd',
 '1f32787b-de2b-49be-8c20-ddaeae34cc22',
 'f0a78e58-ec7e-494c-9462-fbd6446a9a89',
 '6a83890a-d9e9-4f6b-a6c6-90d031785bbf',
 'bf257382-74fb-4392-ad6a-143240e39f81',
 '855d20b7-53f2-4678-a10f-55402d085018',
 '4c63d7cd-4902-4ffb-9b94-578b1b2151f0',
 '1c27cf97-b20c-4e40-b1f1-288b721517b3',
 'a36c98b5-f159-48f8-9f5a-1fc6ea9956c8',
 '4e9c2825-ff13-41ca-8e91-edd848060d19',
 '7b056bf6-c232-46bd-8903-59145ff7ce46',
 '29b6b142-4173-4ec4-832f-7d0a32255c10',
 '89fa73f0-4341-4de4-bb2a-e429ef96bd43',
 'e384ec29-136e-4241-9321-49b367b8cbd5',
 '882e7c95-935a-4eab-9ece-f85f5f7d0f4e',
 '15281e10-e6bc-48bc-9b1b-94402f83699b',
 '4700f517-5c5d-483c-81b7-d77aca04991c',
 '8c246d2b-81bd-4c1f-b563-2c905675f984',
 '458bf0ec-efb4-4bfd-9446-c80295e6aa87',
 '61e07f64-cddf-46f2-b50c-ea0a39c22050',
 '5dff8fb2-73e6-4c22-a34f-c367aa2677df',
 'e5185368-70f8-4998-a738-ca22f300da7b',
 'a6ab18ec-e32f-474b-964b-987309c61581',
 'bd4e7054-4043-4acf-9a49-7d883152189d',
 '8d477e04-3bab-4ad9-8fe3-799059238a9c',
 '5af379e6-1bd1-4cf8-a23c-03266fb77b2c',
 '7ccdee1e-c91a-4c93-8bca-d671cab1ee1c',
 '529a23e0-baa8-4824-9554-416ceba464ae',
 '0baa8cd7-1eef-4960-aeb4-4128e58efba3',
 '1a3641be-fa6a-4d72-a5eb-9069686a88ee',
 '362d282e-5d9d-4691-86a6-21bcac0703d7',
 '7f747187-72e4-4791-996b-4518742dc672',
 'f4ac3eb5-e145-4685-b9e9-b61f3551aa58',
 'b7f30490-0b67-4ccc-b032-1eeeb179b464',
 'bacab81b-4dd0-4047-8d51-a9cb03a8e18e',
 'cb324527-6a66-491d-b53c-6a6d7ece566f',
 '5b90df37-0b8b-44d6-abdb-6fad31217c26',
 'd8e96969-c9d9-4c28-a9a8-403abc1e784a',
 '07b5ae90-4161-4463-945e-41a48fdced21',
 '82206221-05a0-4f89-aa10-e8c8dc0cc418',
 '7fe849c0-4a55-429d-b480-11ee216909dd',
 'c041f6d7-df78-40ee-8832-6772a0db14bb',
 'b3984824-9eea-4ad9-ae37-b07782ecc313',
 '5f2f1833-d203-486a-ac56-665fc3767018',
 'd57f0e9a-445b-465d-b757-be4f32e75fb9',
 '38578b5c-4509-49df-ad79-c62cc914e4a5',
 'e3cdb277-ad80-4025-b5de-cd98cc67d23d',
 '1f2b9c2f-a2d2-4192-b009-09065da8ec23',
 '3bd9f24b-cb02-4cc4-b6b7-da5c1389463d',
 '5af99ef3-adff-464d-9976-5c5d6391b014',
 '0305a46a-fe62-4666-9742-f5fe5db890ab',
 'b954a1b6-d613-4012-8bb5-d60ffb9e94e6',
 '66a9efac-fd43-4fd1-9824-c404b08efa5d',
 '50028008-aa11-4519-9d75-452c84dd27fb',
 'bfd7eaa8-9116-4382-b00e-afc35498dbf1',
 '58c69cde-570a-4558-bca6-987480110522',
 '83568c85-7264-4e45-8a2e-eeb246118465',
 '47874b53-ac2e-4ccc-ad5b-6b2669d59340',
 '0b5caeed-ff6f-4b9d-8375-9ad25827a4ae',
 '8e0884e2-50ba-44c0-87b9-d64d913288af',
 '1c6341f3-ca86-4f0a-ba3c-5f2ecc924bc3',
 '9929eaae-7536-4dbb-a05d-8261c8df07e6',
 '4d89c4b6-6827-4935-9ba1-0502025af270',
 '1045a19a-a686-47b8-aa54-33c1063613d6',
 'ecc37a22-b730-4e3a-bc87-c3ba3403acbc',
 '87b7c93a-809a-4709-8e59-c56b02fec7c2',
 'b0803304-62b4-4428-a333-e9bf623c8a98',
 '949a81ac-5df1-4e7b-9f4e-e364b5603e68',
 'a6e7224d-da3e-468f-bc51-26331659e06a',
 '914fe264-109c-4d4d-8f18-052785666a24',
 'd7f17a3c-3885-4b47-95a8-c4204a3698f5',
 '0819b74d-b28a-4702-90a2-9d205dd9fc5e',
 '68bc8994-ebef-4e48-8478-e7fe1619ae58',
 '21532265-cfd0-4301-a58d-dd615d0189d6',
 'ca35decb-6955-44b5-b2fa-eb4529c3cb5c',
 '96d328b9-5da7-4389-a9ac-765e98971ab7',
 'c309c7aa-b438-416a-b3a2-bd433614c6ab',
 'c85cb6f6-60e1-4a94-8f8f-6b436bb1d77c',
 '8956c97a-6d85-4d4b-a6f7-6d42c6be97cc',
 '598ed114-fd5a-4d82-90d8-f1e893cb0892',
 '100ff71c-da18-4182-9672-369324a71bb5',
 '91dd61bf-7c49-4276-bba6-1db2804921a9',
 'fd3c2179-09b0-4b2c-96a9-2d8822f28851',
 '564f0976-781b-44e7-96c8-7377097d0101',
 '9d598d19-d6be-4c7e-a963-b8fedfa8f24f',
 'e1a89c3a-1649-486f-a964-ecfb33821e77',
 '3936f6c7-3f6c-4205-8cda-3178160b6cd4',
 '09092757-a6a5-49e6-b2b4-a59856c6ea81',
 '13f2cc37-f575-44d5-b33f-045d0b0a912b',
 '106e6c31-5aa8-4d21-8d76-2fd90d35dba1',
 'a8f0cda0-6c9c-45f6-b72a-3c20ba9624ea',
 '7c076eda-5b41-4b0f-815f-0f6400148b0c',
 '83ebda93-e1cf-422d-ae6b-18298c55ed8e',
 '73151e02-dd2a-4509-968e-b9c16ec1c5db',
 '60d611ba-5bdf-41f3-b1cf-0f712879397a',
 '7594da99-d606-4338-a373-710a7dec776a',
 '3a54bc78-a1f6-4a3c-a1f8-d541597eb6a0',
 '5c37a504-0ed8-49c1-a6a9-d237d90664e3',
 'fdab1161-53cc-433f-8c1f-636130bbaba1',
 '230d19cf-28f8-459a-ad3a-da60aa640639',
 'c31953bb-c126-47ad-9112-d82f8776db2e',
 'e63ef205-d49a-4cd6-ac85-059535e3d68c',
 '4e73dd4e-0e2b-4a11-8f5b-658619b08027',
 'ff3e8c61-d72a-42bf-a84a-ecf5409468dd',
 'b4a5680b-d0e1-4260-bc54-82fbe328d3a0',
 '4a108326-b19d-42ce-94f6-807abf6e4679',
 '97ac6c4c-5b3d-4e36-9816-0791226573e5',
 '5ecc4b24-ff5d-4f8c-8449-53de3b34d213',
 'd6d7696e-9bd3-4cb4-9cbd-9e58b9656bd4',
 '756f1fd7-703f-4ba3-ac49-a7c9bff1b1ec',
 '4e163060-2488-4627-a8ba-bbfc54a4d57d',
 '2008f497-c05f-49e0-88dd-86aa1e395f15',
 'c4a64d0d-09b8-4f82-8e32-4d2ec6067226',
 'bd1bc41b-79a2-4b09-9ca1-b1e26805810c',
 '279ccbff-f203-4c6d-aa48-83d97f085302',
 'd173164f-dcfc-4e32-8006-64ab44a57c66',
 '9771b0d9-b14a-4908-8932-440b6fe33aeb',
 'ece7f38e-1744-4885-83d9-2ffb89e40b11',
 'a2ef8430-00b6-49de-852d-2c72596c5917',
 '54cb252a-78b5-463d-b31f-f54f63d85a29',
 'e93f13f3-466e-4a34-8cb3-09460b909d29',
 '426e9777-7ad8-4b0f-98f4-48e8ee96ace5',
 '229628a2-f8e0-43ca-bac9-f14a161f9124',
 '6c04dc83-e523-4a23-9329-5499a899392c',
 '7a01fdb1-c5c0-4833-a252-8593f91eed3d',
 'e22473a3-7a8a-46cb-8c86-1bda7a5c70de',
 '3e54b313-2fde-4180-9948-74e889dd9430',
 'b2a21491-7576-4be0-a520-97ce9470efeb',
 'b79a9385-ab79-4949-a953-2320bfb28bc0',
 '9e1b4571-e55d-4a26-8c5a-1ddd6ecf53ba',
 '8864af44-c4a2-4862-82de-be58579ac4f3',
 '3137f551-87d2-48b6-82bf-48b2bf11e643',
 '57615619-0c1d-41fb-8640-ccec5b3add58',
 'ae6ab95e-0c43-4be4-8748-3eef5711fd10',
 'ecd63535-1875-4f84-b7c1-3aabcadd316f',
 '83cf1546-5235-491f-ae0c-90949a2ab3c2',
 '7c3fbe06-7d31-49b6-986f-3be196b84687',
 'feee3eb1-d625-4766-9da5-d855ac2f557c',
 'bf44b8ea-c737-4eec-a51b-01006202f303',
 '50f85bf5-c153-4611-bf35-2f781ae4e234',
 '750ec729-cd61-4227-85fe-a1e0ebbf7d50',
 '553fada2-1c79-48f2-9010-f5c751b63bb1',
 '84c68fc4-68d9-4987-b740-2e32d30f7069',
 '69cdf5cb-1f8c-44aa-a28e-030d8dddca89',
 'dccce65b-8982-46e1-afcb-01db956e2cd6',
 '9c989bd5-2987-451b-a4af-1143e774f2a0',
 '8f28e4d1-c4ab-4ce6-8acf-27726b061aa3',
 'ad2c51f7-26ff-4f7e-98c8-32462c62874e',
 'b45d3be3-1172-4a62-8b29-a7c0faba7124',
 '62c75a44-c053-4f1f-8cd7-788df09ad65b',
 '78f442cc-1fb3-4bf0-a9c7-ab6cf5a73526',
 '788b88f5-d957-4152-8a8e-4c8656405b24',
 '4d16a079-ca73-4bb6-b6ce-872bdddf1aa4',
 'a9c454c8-9493-4622-a499-43d20c525f81',
 'dcbcfc8d-6010-41df-a39d-008b0c7bc85d',
 '224d8516-f349-4d8a-9e73-e3ca1c47a992',
 '6a64daa7-32ec-4d35-a7ec-f3df800f6d5e',
 '91266575-23d3-4ce6-91b1-5d0ad7c3936d',
 '06294fd4-5d1e-498f-9a46-b0631ebcb60e',
 'ec7dbae8-2ef3-4fa0-8b70-22b425f09f5f',
 'd8b6f5a1-2f96-4d02-a78f-dbe1c87946f8',
 'd57cd3fc-5185-4b29-8a85-c2f04bf6921c',
 '2c8d0162-7a7c-420b-ac35-1f7f1e9f7ba4',
 '286428b0-dd16-46e6-8189-2908a23967ea',
 '6144af8d-bd8e-415b-9cc6-b463c6de4bed',
 '62c033c2-103d-4c76-8dbf-19c1cc869ddf',
 '11e99467-b34d-48e8-a24a-b12a1ff2aeef',
 '33b8607c-f4aa-4379-a18d-f7dddd2dd52e',
 '037155f4-4db8-4f07-8d0a-3e559605b8ad',
 '1a732119-0975-4bc2-8077-cb2ae8d249af',
 '8ce81c16-71ad-4eb4-88dc-d6a85c49dbff',
 '9c8465e1-65d5-44d6-817e-a8657d38fd32',
 '116fb46c-a297-4772-8de8-3609409599be',
 '90c1930d-6795-4daf-8efb-635b7ac3dfae',
 '46726d44-b83a-4f34-bb8b-738f4205af48',
 'e77e093c-d944-4d4c-9143-e67c75c616c5',
 '38f206b8-17eb-4f60-8a20-27e808061ef5',
 '999f8b86-8f29-44b5-942a-79d1174efb6b',
 'c0e5b84d-ad62-441e-a50e-0d562fc15540',
 '7caf0079-a39e-4f7d-9d5b-7f8d8a625f2f',
 '92ecb67e-11a0-4daf-95e2-70251ecfc5cb',
 'e3f6e172-5893-4a65-abb5-4adfc2ae2685',
 'e5b31e24-1bfe-49d5-a0b2-8af464411fda',
 '05606e8a-4053-4683-ab95-3903bb2d4efd',
 '444db2d3-2856-4307-8a36-09b15651fb8b',
 '12c44ec3-3624-4c0d-990d-27c38e7a5848',
 '6c517284-c766-4c7e-a27f-09b4bc6ed8ab',
 '4e986ba0-ca6f-479f-979c-a111d0a2b7dc',
 'e2a81417-e811-46a4-b26e-f77c1c836046',
 'cbc832d6-af68-41bf-91d4-8740d71c5952',
 'df5d45f4-5d75-4f49-90ea-c71e6e56ded8',
 '4ef1d1e4-01aa-4aea-8a31-51598feef18a',
 '44db03fa-78a8-4296-b8c6-f6aba1c995a9',
 'f82aca8d-3fdb-433b-b245-980d9a040d77',
 'a9466ce5-0cc8-4cad-96f3-fa3de8becf7e',
 'a2200d09-93d3-406a-93f0-b29d93b9cb0d',
 'ad42c4b0-dfb5-49fb-87bf-7b5d055b6e8e',
 '5b1cb0ce-8056-4dec-a64d-623068958061',
 '557c0d37-0427-407d-a235-c78028d91220',
 '6867c681-1abc-43ae-97aa-7015ea14b226',
 '2463b085-fab1-4d06-b557-614e28ba71fc',
 '43cc5638-6dda-4f23-be83-647bac748e70',
 '99566c41-bd03-4b37-9ed7-4ba3485e7de5',
 '8be03387-6c44-43cc-93ad-65824af9c22a',
 '0306487b-37be-4eda-bd8e-ad0a60886480',
 '139c9e4d-b7eb-43d0-b2fc-1cb230f0adc8',
 '2e3300c6-3a18-4908-b9a9-a955cfcdcfcc',
 '1dc0c4a8-0e13-454d-b3cc-16181bdf727d',
 '5a8c0d96-e126-4472-bc01-e581564c6575',
 '5512feb7-1489-48ba-a78b-457c9defcc51',
 '9442c690-21b3-42bc-9e5a-f880de0fa0a8',
 '5dc238f3-93be-4fbe-ab76-ec09c9cdcbd3',
 '3ffb80eb-0ae9-457e-883c-d52f57c124c0',
 '399c1321-5d2b-494e-9025-2ba2b8b56117',
 'a76dc579-5e75-4d29-84ec-0e8b7cf477e5',
 'dd3babeb-856a-43ad-8c2d-5aa6695b9173',
 'be27248d-bf76-4373-91a2-f62b612d9916',
 'a289fde1-2ea9-4c18-a489-b8ad09c6a3dd',
 'c88cebc3-e150-4efc-993b-76cda07dc6ef',
 '347a01fa-6f39-49c7-9a61-72db9eca0d19',
 '9e49825f-6567-4ede-90d5-46a1af9a127f',
 '5acaac71-a0c9-4d6f-897d-308409a37f01',
 '64dd5b2a-0963-401c-bf69-ade920ce7e28',
 '2db1a14c-afb7-435b-9cc7-3d85d5aecd09',
 '4f2c5d08-21ac-4e99-9ccb-c9344aa7951d',
 '5bf8b3a3-3916-40ca-8672-a9f3df311825',
 'aeab0e46-f1e4-41e9-821b-571255c41f69',
 '919f29bf-d153-400c-a04a-4237f5adf116',
 'd973bcc5-eb9d-4c11-8017-c88828858da4',
 'af5d32bb-ab3d-47fa-96c2-bf44680ea0f7',
 'c48c4f8d-b3c7-4d3f-82c4-84091bd4e401',
 '45a4ed6e-4f6e-4fd4-8997-864b3a68c85c',
 '6f344c45-e731-41b4-8c65-9967ebc03096',
 'f4b9eb2c-5b14-4bea-8281-231355e612e7',
 '5ef8124d-495e-4de3-af19-48c14b92dbd4',
 'f774e860-8103-49bf-b04e-63b316735e4b',
 '72e5a5af-c657-41c0-a859-d4fcc4b7b933',
 'b442d94e-f0c5-4fc1-9406-a4b64b595d71',
 '6760953a-6c40-461c-87ef-45639ea4909a',
 'ea12f8aa-58b6-4ad8-97c7-2a4266f95c57',
 'e4a32f87-4d4a-42dd-b1d0-b4d0564b03bf',
 'd27db1e4-e90b-40f3-8be9-5b1c6086c52a',
 '61e5c9d9-f22a-4993-9062-7bcff41a8b8d',
 '5ad189e3-77e6-4c5e-9eed-8979ba58e283',
 '5db25cd8-32e2-4502-9208-b62d0e13b015',
 'c4789e51-c882-44e9-b133-2d435af16d54',
 '120e8d3d-4bef-4dfe-8128-170c76a6c730',
 'fb96b132-fcde-46cc-86ef-000cb250c361',
 '532dd818-19a1-46a1-b2aa-630606026a07',
 '30fa8088-bc67-440e-b66f-6f6b42c76e45',
 '99cee40b-98dd-49a0-b741-41296aaea59e',
 'b2543715-4744-4983-991b-7692e2062de1',
 'dc5abd37-fda0-4ad8-9620-8db2b13090d5',
 '94c77949-55cc-434b-84bc-f84bf875da63',
 '542cbae0-40d6-49bb-b7cb-c869ea3192bc',
 '39637899-fc4a-47f2-b5aa-266a97d54cb0',
 '7fcf82cf-6a19-4e1f-a054-d5356546bf31',
 '09a5a7c8-7687-4311-907c-d43fdb650b4c',
 '4e2281de-bab1-4f06-b3e9-8263d0ab2b0b',
 'a25e68dd-1343-4dc5-be73-2ae40aaca5ee',
 'c44af7c6-88e9-4ce2-81d6-7b8adc4e085b',
 'ac1e6c6a-9403-45b1-902e-60f4b6914854',
 '696c06e7-a338-4cf5-b9c3-ea8b9e775a94',
 'c21004f0-4d4b-4882-8718-e1d6d276b175',
 '4b715f78-cfb2-4cef-bce4-7f50c8c9ecd4',
 'f5d2a476-c8dd-4ef7-bf6e-8d9016c7f349',
 '8f3d661a-9a9d-4080-baf0-422014067d7e',
 '9220d7b6-6427-4d22-a558-a36009b9fe76',
 'c55b5b0f-9cd7-416c-a87c-e781c6e9bdaf',
 'd730c4a6-e8f6-4fde-b73a-afbe148479cd',
 '35e05c24-1d29-498e-81f3-ecc93841c3d7',
 '9a995df9-084f-4a39-a623-4ef1b06a36ed',
 '074b796e-4a70-4604-9b50-3713505a1275',
 '25d54fe7-248b-4e1d-89a1-20b36aba6159',
 'cbbc09bb-d46e-4542-86bd-f6df649bf88a',
 'd4303151-c778-461b-8207-2e443db4b255',
 '9468d948-25cc-49d2-a659-167496e0892a',
 '9659f9a7-c6b6-4772-9b59-7c085d3051de',
 'bfec08b4-841c-4e6d-9b75-b4e81e3ff649',
 'b182c3ed-17bd-457e-9b60-2afb6b2971f4',
 'd4ac55b3-cc99-4b47-aba2-ed60be31c170',
 '533b3efd-b7d4-418e-92a9-0a1d88440963',
 'cec08bf9-4f41-4cbf-88da-bd1643c99b21',
 '96aebf6e-817d-4a3d-9e21-f5357ecebab0',
 '3ce73782-d80e-4031-be53-5761b158cae7',
 '85beb942-01d5-44ce-a5aa-296139c73667',
 '3fb7858c-33f9-412a-b0cc-c847df3e2be0',
 '0a449219-862a-4184-91c1-9af3bb6755c1',
 'd5f5e1da-c3c8-49ab-b0a6-e027f3d4d724',
 '2a9226ae-a3a7-40b5-b800-ebabe6229a29',
 '4d160552-aecc-49ee-8024-35ab14c23ca1',
 'e4b31b93-9ee8-4754-a18a-88192298a160',
 'c9f6922d-c67a-41e5-82d7-b283af240233',
 '27453ffd-5354-440a-a6b1-0b56eb6b6821',
 '42fb9402-672d-4768-8d2f-03ea257150a0',
 '9a4bb232-f1b6-4cd1-ba6c-c4696952153b',
 '6452a218-de3c-4511-b482-d58f26b7ecda',
 '97c00ceb-20e2-455e-b706-9a720e9b32d2',
 'f399b893-e696-4f8a-9dbe-e49fdecddfa0',
 '3cd06f5f-a3bb-4589-a592-07a1c6121a99',
 '55ab912a-2bac-46d9-9fcf-8e9be376f1b3',
 '11847236-bd96-4f5b-b6e7-07a43b6185ef',
 '39959832-be7e-4420-94ab-9244f409bfe9',
 '44fdcedf-e9ae-4748-8ab3-0cdb466672a6',
 '1c4faf15-dcb3-46c3-ae9f-b79380e1d1d4',
 'd262c24d-1d6a-4c9a-97db-a721bd27f9db',
 'f8f52df6-0dbc-44e1-8ea5-78a61c209ed3',
 'ced7fe89-46e6-4bc2-b5c8-ecfcfd33c577',
 '35a3eb46-f1d1-452f-aa7b-42c1382826c8',
 '561850c2-9ade-4985-bf36-402abf02153d',
 '5b9271a4-a750-4dc8-bdf8-20653b1acfd8',
 '470ccd72-1478-4a82-9e75-ecb6f732772a',
 '450d6500-b3bf-4217-a869-7303a818e226',
 'c4fa4a10-d95c-4b41-81bb-8ad16c40b5db',
 '11cdab41-edc5-4af3-ba9a-bf53e5681263',
 'db037f57-5594-47e8-a523-076c8c83914c',
 'e67a8a04-2e7d-45a3-8374-73380b09a47b',
 'd8de2192-12b4-4fb5-97d8-8a6360a10e78',
 '1db5507f-ba78-4c81-96f1-36a4874fca87',
 'fbbd2472-9ee2-4d84-9211-deb431ba8a75',
 '6d2b48fe-1ada-48c9-a508-73e19e83069d',
 'esid:conteudo_editorial_g1#materia#https://especiais.g1.globo.com/bemestar/coronavirus/estados-brasil-mortes-casos-media-movel/',
 '22bb0455-6973-40f3-97eb-579f6661317c',
 '9fedc28f-b68e-4bd7-b97e-778e1e8f6274',
 '127dc467-cdde-4738-aa8c-e18ab0e3e81c',
 'dda7ac72-2500-43de-b630-56c6e8e5a913',
 '2a6d85db-5d21-4958-af4d-42dcaab01dae',
 '3ee8ff4c-2dae-4394-8ff6-abd22556e323',
 'fbffe526-e94a-408f-a19b-7510f3d56016',
 'f38d9b98-70c5-44c2-9a6d-fcee0df331ab',
 '84475a89-38d0-47f5-b26b-58078f824530',
 'e2cd1c23-e372-4525-8b2b-b6886428f444',
 'f8274d89-525f-49c4-9331-68b69b03c5a6',
 'fa571e66-a5b4-448f-905f-59e398a673b5',
 '3c787cdc-99f7-4001-94ac-4edb2e971b94',
 '064b539b-a4cd-4781-b97f-9e9859ce15f7',
 '7456c88d-6473-46ed-83a6-dfc406994162',
 '5fada3ca-d728-4b7b-91c0-b1352a07ada6',
 '2968b302-6e02-493b-b192-cdd7f6038e03',
 '18633c31-9144-419f-95b7-7bbac07695c8',
 'cee20002-7c68-466a-933e-f8969dc58afc',
 'ae883cc3-2dce-41eb-9158-9e4b8aeeb20e',
 '45a2068f-7dd0-4244-89c1-9119d1937bd4',
 '9bc6f6fa-94fc-4748-b4ff-40aaa6c4f525',
 '148518b5-c324-4882-81a6-678168063a2c',
 '5a867ffb-7227-416d-a286-f73c9ee6a4af',
 '78f42bd4-4281-49e2-abd2-2da58ed56dad',
 'b57fa2d2-0a34-4117-b22d-29ad42c8e063',
 'e93fb5f7-e64e-4866-be46-838c3c71e471',
 'f4e179e7-d4d2-416f-8997-51f421bcab2d',
 'c1ee25ec-8981-48fd-8711-76f59870503d',
 'cca0a1c2-3e83-439c-bab8-a3bf7782572a',
 '8b64b810-cff4-40e0-9de9-25b809ae6009',
 '08a27175-61cb-4462-b0cf-4f9ec2d9d9f0',
 'e81954ea-c381-4906-930d-b0703e6cf7e1',
 'e69d567c-41c3-4076-846e-23324fe91104',
 '829265f6-c85e-4474-aaf2-49f7df8c4fdc',
 'a94ec35e-0ef4-4b83-ac96-034d409c82e0',
 '17d0a275-8223-472c-8c9c-cafdbd6b5739',
 'a1c96be2-5708-4bb3-861a-659123ade1cc',
 'd2bfebf8-2ed7-4e2f-a6a4-b950486a86e7',
 '99c4a6d3-41f3-4bf0-bfba-a419e0e621f8',
 '1ca0b64a-8bb4-4a2b-b3d0-af935960bf15',
 '74b0e1d9-7ff2-4740-b22e-465a5d644ed7',
 '2de36771-38b8-4e2c-a2b7-d00590dd9009',
 '57a0c7a5-6cf9-482c-b85c-dcd71092b15f',
 '3422afb1-dea7-4e62-a4c5-1fc3bd0c9a44',
 'ea3b1e84-69a9-461a-92b4-8206903def33',
 '4c586bb4-f71d-4b39-9df8-e38ac3f632a0',
 'ffeea3a6-d969-4a9a-baf0-101da68da3f9',
 '44afad69-6dff-4068-9e10-3092b659e6d4',
 '5b82930f-fdd7-4e5e-b720-8b1b8eb709d8',
 'f00301ea-a6ff-437d-b83d-f18cc5d1a314',
 '47e1ddae-8f6c-41ae-9bdc-6a2acff86bfa',
 '8458c0c6-5e5d-4e50-a5f9-6aea23ac3ff8',
 'afb60617-1813-4e1b-93cd-e4f7c7a564cb',
 '79fa537e-6643-4a83-8896-2e1ea3d18215',
 '6e5ae05a-ccc9-4384-85b8-9fa1d871ba1b',
 '9d780356-4f15-4feb-bad4-311edddf1826',
 '09131b7e-f907-423c-93e0-5ef8913d8c7f',
 'esid:conteudo_editorial_g1#materia#https://especiais.g1.globo.com/economia/concursos-e-emprego/lista-de-concursos-publicos-e-vagas-de-emprego/',
 'esid:conteudo_editorial_g1#materia#http://especiais.g1.globo.com/economia/concursos-e-emprego/lista-de-concursos-publicos-e-vagas-de-emprego/',
 '785e6e9f-69e6-416f-b6a2-2b7d13426a75',
 'dd4d0068-ae1b-4e78-a7e5-7e8c2a4a5615',
 'fa65c031-aa6b-4447-80d6-943d2138885b',
 '99046129-d852-445c-9e6e-e140ec99b5e6',
 'c40c2035-77ad-439b-847f-ad984d28d056',
 '698ce0ed-49f8-4a09-bee8-f3be6b6c9ebe',
 'e650aae9-2b05-4564-9ce7-108a31c4de20',
 '0d7dbf6b-1abb-4aa1-a4d9-47d9c3429333',
 '0e4e09a8-7a88-4758-a3f2-d0dce43df4c1',
 '26516399-e091-4bc4-89e4-d9d45cc3f9e4',
 'c6ef110d-7837-47f2-84f6-cfea4da5e328',
 '54fd8bf0-d4f2-42f8-89c6-a6d49245954f',
 '34c9da29-421f-4983-bd32-19a7daaace13',
 '46fd2c8e-9759-4c39-91e4-94255a55c994',
 'e8922989-311f-407b-954d-67767cd97d83',
 '68bcd037-cf0e-4a5f-899b-79d97ce2827a',
 '2ff74cfb-89d5-4741-8ee3-1e5d99464a18',
 'f0c45837-0476-4bf1-aa4b-73c5a6e635da',
 '0e69fd2a-7bf7-487b-8da0-6e41a7950fd4',
 'e8e6fd2f-86e8-47f8-b132-e196dc9e3b2f',
 '5bd87b4b-967a-4f44-8d7d-8dd415925c60',
 'bcf0a249-f985-4e6a-bde8-730726a42a16',
 '0b5bd097-f8c9-457b-8de8-32ef82585a62',
 '3b94c985-903b-45db-89a2-24d3d4459509',
 'd3f1ee4d-fc50-4e1f-af67-99bbbd2e9555',
 '4a983c7c-cd3d-4ef8-9584-eb83fd7fa90e',
 '58075d9c-16c9-401d-b1a5-fa53684f127b',
 '0650a691-26f6-4a08-85c8-4716ae0d5388',
 '02910a33-93ba-49fb-9bfa-f8db58520cdb',
 '77dff2e3-1436-4612-95bf-ad95275993ca',
 '239430d1-9a03-4b7e-a928-2362102ab641',
 '03b2975b-7493-462b-a851-711ce6beb6c0',
 'ca361779-0059-451e-9369-c2dfaa3cc971',
 '2e735dd9-49fc-472f-b724-aa236936546f',
 '7966abf9-474e-4190-a9f6-baa5501068a0',
 'a1eeb178-ed8a-4d6b-b2aa-1921fb0db978',
 '547c15fa-57d9-4b47-9dde-944c1533fa99',
 '141814bf-48d5-492e-9605-bed1b400d346',
 '242a3ced-bcbe-4083-8099-eae08787ebbd',
 'e17fb42b-f132-4c25-9e49-a0fc520817d3',
 'e8fc4f0d-6d18-4690-824e-4869a1d2d12d',
 '064e7cfb-32c4-4785-ac91-f26fa05e4237',
 '51219799-daab-48b2-b700-3a61833b3ea8',
 '44c1c60f-ae33-4350-a362-21fa3b26fb2c',
 'd303158c-8b2c-45de-ad18-2fdf67d06397',
 '81094a7e-7b3d-48b5-b98d-9b1a6a20e7d0',
 '498f00e5-8860-4365-a03c-dca9fd298b80',
 '51b38ce7-11f0-4dc0-8e21-6522b0587ec7',
 'a1a27aa8-6ac4-4ff8-be0d-96b8c286059c',
 'fa319820-539c-46f1-82be-9bfb4ef8ddd3',
 '73b9f4e5-3047-4b2a-acce-3232b959c41a',
 '029c4dd9-4231-469e-8eca-3de5f05ea046',
 '2de967f7-b28c-45ef-a21f-76c9926ea116',
 '5b68d910-8e4a-4fa5-8fae-65c841282e94',
 '3148473f-bd3c-45c6-a2f6-83e667025005',
 'e0425f71-24b4-46e7-b800-408a4de2ca73',
 '5d62d256-238e-4516-a750-68799c6ec2e1',
 'fcdc961b-9239-4c94-a775-bff667a105a4',
 'f4d46a04-e9dc-4cb1-a383-af5c2a6413d6',
 '78154e46-5198-47ef-859d-42d75fc357ca',
 '8c37ed33-976c-4100-b831-5a776c7a6716',
 '1fd81f89-cca7-4122-8749-db21b14c25b1',
 '94bb48e7-fa2e-482d-be7a-4f4353dffcce',
 '251269d5-3194-4fa1-a62d-fab4971dcbaf',
 '109adb08-8ff3-408b-b828-e16b51788202',
 '4f126ed4-66ca-4379-8779-6afa1b4d1662',
 'd61c5cc7-2a4f-42c5-ab06-bef4a6314808',
 '9a9d7eab-eb79-4268-a3e1-da0515ea4815',
 '5d8388f3-736d-451b-a794-d826453e12e1',
 '1d899325-ad3c-4287-804a-3d994492dad8',
 'ffabc550-b315-4070-94b6-713712da8ec2',
 '3901a861-007c-45ad-94ac-c635d8663696',
 'f712cfd4-b1f3-49ec-82c7-5f3b366a5ac3',
 'd3302868-9c63-4712-9cf0-adfcaad19187',
 'af617145-c750-4973-81eb-a1ff00e6ed1c',
 '1d22f204-4cea-4b1d-95da-f6fbe57cd622',
 '30a03e2f-327f-42b2-babf-fbc8e9a208fd',
 '880ef64d-da1c-4edd-98f5-71bea000f858',
 '0dd9af9f-bcb0-43d8-9d88-b5d4cbc1514f',
 '73ed314a-a9f3-4b76-83f1-67063a4ca520',
 'a377fa79-5b40-446e-96c6-c892b3e1e57e',
 '7b41b70c-5434-4ecf-898a-e4315641ad41',
 '841bfeed-2081-4797-b6a0-1087aa7c2846',
 'fd3cef8e-7a96-4c4e-a76f-983b7de8931f',
 'be57fa17-972a-46b7-bb25-ba2346e6b7e6',
 '2b4f0f8f-ab7b-45e7-8a8a-353e0aa41249',
 'd8ab72b2-7618-48b6-839f-e80cecbba5ff',
 '82d5ad79-433e-42af-b8d7-9d56ab3a9033',
 '1fbda98e-49b8-4868-b22f-71be0a9d759e',
 '7c2c0c12-6dee-4f32-ac9b-15bc975ebbbc',
 '81554b6d-3d0d-45ea-a5f5-15c09331690d',
 'b506a89e-b492-43cd-b344-84875a797cc9',
 '470bac7a-d454-43c7-b36d-7b075b7f353b',
 'a47114d6-cac9-45fa-a4b7-987383f4ec29',
 'd37d7e59-2ab2-4dd0-a415-8063af12966e',
 '41a5ceb6-c603-44d2-af37-bc159ed58fa6',
 '700d8181-ed28-48f9-b716-40c18325909a',

In [7]:
# Criar embeddings das notícias usando TF-IDF
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stop = stopwords.words("portuguese")
stop

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/felipelangoniramos/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['a',
 'à',
 'ao',
 'aos',
 'aquela',
 'aquelas',
 'aquele',
 'aqueles',
 'aquilo',
 'as',
 'às',
 'até',
 'com',
 'como',
 'da',
 'das',
 'de',
 'dela',
 'delas',
 'dele',
 'deles',
 'depois',
 'do',
 'dos',
 'e',
 'é',
 'ela',
 'elas',
 'ele',
 'eles',
 'em',
 'entre',
 'era',
 'eram',
 'éramos',
 'essa',
 'essas',
 'esse',
 'esses',
 'esta',
 'está',
 'estamos',
 'estão',
 'estar',
 'estas',
 'estava',
 'estavam',
 'estávamos',
 'este',
 'esteja',
 'estejam',
 'estejamos',
 'estes',
 'esteve',
 'estive',
 'estivemos',
 'estiver',
 'estivera',
 'estiveram',
 'estivéramos',
 'estiverem',
 'estivermos',
 'estivesse',
 'estivessem',
 'estivéssemos',
 'estou',
 'eu',
 'foi',
 'fomos',
 'for',
 'fora',
 'foram',
 'fôramos',
 'forem',
 'formos',
 'fosse',
 'fossem',
 'fôssemos',
 'fui',
 'há',
 'haja',
 'hajam',
 'hajamos',
 'hão',
 'havemos',
 'haver',
 'hei',
 'houve',
 'houvemos',
 'houver',
 'houvera',
 'houverá',
 'houveram',
 'houvéramos',
 'houverão',
 'houverei',
 'houverem',
 'houveremos',
 'houveria',
 'houveriam',
 'houveríamos',
 'houvermos',
 'houvesse',
 'houvessem',
 'houvéssemos',
 'isso',
 'isto',
 'já',
 'lhe',
 'lhes',
 'mais',
 'mas',
 'me',
 'mesmo',
 'meu',
 'meus',
 'minha',
 'minhas',
 'muito',
 'na',
 'não',
 'nas',
 'nem',
 'no',
 'nos',
 'nós',
 'nossa',
 'nossas',
 'nosso',
 'nossos',
 'num',
 'numa',
 'o',
 'os',
 'ou',
 'para',
 'pela',
 'pelas',
 'pelo',
 'pelos',
 'por',
 'qual',
 'quando',
 'que',
 'quem',
 'são',
 'se',
 'seja',
 'sejam',
 'sejamos',
 'sem',
 'ser',
 'será',
 'serão',
 'serei',
 'seremos',
 'seria',
 'seriam',
 'seríamos',
 'seu',
 'seus',
 'só',
 'somos',
 'sou',
 'sua',
 'suas',
 'também',
 'te',
 'tem',
 'tém',
 'temos',
 'tenha',
 'tenham',
 'tenhamos',
 'tenho',
 'terá',
 'terão',
 'terei',
 'teremos',
 'teria',
 'teriam',
 'teríamos',
 'teu',
 'teus',
 'teve',
 'tinha',
 'tinham',
 'tínhamos',
 'tive',
 'tivemos',
 'tiver',
 'tivera',
 'tiveram',
 'tivéramos',
 'tiverem',
 'tivermos',
 'tivesse',
 'tivessem',
 'tivéssemos',
 'tu',
 'tua',
 'tuas',
 'um',
 'uma',
 'você',
 'vocês',
 'vos']

In [8]:
vectorizer = TfidfVectorizer(stop_words=stop)
tfidf_matrix = vectorizer.fit_transform(df_items['title'] + " " + df_items['body'])

In [9]:
# Criar um dicionário para mapear páginas aos índices
doc_indices = {page: idx for idx, page in enumerate(df_items['page'])}
doc_indices

{'13db0ab1-eea2-4603-84c4-f40a876c7400': 0,
 '92907b73-5cd3-4184-8d8c-e206aed2bf1c': 1,
 '61e07f64-cddf-46f2-b50c-ea0a39c22050': 2,
 '30e2e6c5-554a-48ed-a35f-6c6691c8ac9b': 3,
 '9dff71eb-b681-40c7-ac8d-68017ac36675': 4,
 'a9fd6d34-6f40-4c90-849b-2ad36f04fd6f': 5,
 'c2893f07-08fe-4b4c-8904-92f0fedc3040': 6,
 '682da2fa-6f5b-4017-be35-7968990f62b9': 7,
 'ae5a4574-9347-40c4-b17a-bc20f13faa67': 8,
 '360c9076-0302-47dc-a4fe-da301d151aa2': 9,
 '7d49bc26-de32-45ac-98e9-e66c3359dc72': 10,
 'da15522f-f679-4ff4-842c-9a212d5af519': 11,
 '790f8f6d-2674-462d-ab94-47239c2f60d5': 12,
 'edc93569-bf37-437d-a6c3-fda029f8bc70': 13,
 'e5323b08-013b-408d-91c5-9c03460b689d': 14,
 '99ab59ae-c364-4657-93a6-6a23b58a1a51': 15,
 '71cdc0aa-902a-4b82-a518-c6e4411b5fac': 16,
 'dc4aea98-84c9-47cf-a173-cb58820d5f28': 17,
 'b88ba573-3cbb-4595-9b92-1194bdda9d44': 18,
 'eaa6c7e1-38ba-4d9c-9570-2618df4297f2': 19,
 'e0940638-1bf2-43b2-99c7-d970783463a4': 20,
 '6e9150e5-57f8-4762-b5ea-d82164c91788': 21,
 '6eafb73e-e0be-4f89-a128-ed44898e0fe2': 22,
 'cae23e40-ccfc-4f1b-8b99-bb84c0b2ad7a': 23,
 '8a80c82f-98f7-46f3-b9df-b075d4117fc4': 24,
 'e5cc00c6-d0ba-4ad6-b532-083162d297e1': 25,
 'd458eb60-018c-42d1-9731-7d65be3ada78': 26,
 '9329c330-47b8-4f68-8739-7a74c56bac66': 27,
 '794bde91-fcc7-4f47-8be5-21e5db6596b0': 28,
 '9abed25a-9aa4-40e1-994d-fc411235bbf4': 29,
 '07008ecb-2ec8-4874-b0da-60dc0ec7344c': 30,
 '8fd32bf5-272f-4d81-975b-40b801fa0aa6': 31,
 '87eb0cbb-d6ef-4d23-afa0-df13f58016c1': 32,
 '402b0ae9-accd-4128-ac43-db0a0fa528f8': 33,
 'f6f9cd94-1ac5-492f-a709-a6b6263fd6e2': 34,
 'fa4205b5-5fd6-4c9a-90e0-f61425d782f7': 35,
 'b042d8d5-19eb-4ff7-ac30-b70a954d1d5d': 36,
 'b5795aea-4807-49a2-b109-5a5e9ff6c572': 37,
 'ff0b8fbd-872d-495e-a26f-15d59f52b26d': 38,
 'e32ed631-7067-4bd0-833e-ad235d93c7c0': 39,
 'bfd0626e-9bf8-4ea7-ad9f-64399842825a': 40,
 'f2814377-6d44-4eb8-a313-b61633749505': 41,
 '5a1caff2-fea8-4c1c-9b92-dd9e0247224d': 42,
 '00f8708a-a9b1-45f3-90e3-2849b00abbaf': 43,
 '01dacb79-c765-4e97-ae4e-04eb486d17c8': 44,
 'a4d90c2b-8c11-4b7e-9c46-4719e806156e': 45,
 'f24ef2f6-3207-41bf-b18f-e0917553ca3b': 46,
 'd005217e-5a1d-4978-921f-f5170e8a4887': 47,
 'bdb1dd9c-ce88-403c-841d-60af399b639c': 48,
 '9b9ccf6d-e33b-4181-83c1-56a36da0b3d6': 49,
 'a581c464-0b7a-478e-97dc-046121f078e9': 50,
 '6770fc5c-1ea2-4117-9f76-247f0065fb41': 51,
 'a06721b0-bc3a-4aa6-b088-8146415dfa9f': 52,
 '2f5958cf-e884-42db-b55d-b615771fd0f5': 53,
 'fd6cda83-9cf0-4f71-9854-e3232055f1ff': 54,
 '82e0449a-4c6c-4628-a93e-ee3e5b2d0759': 55,
 'a927bd36-c4d4-4e32-84cb-14f88700c057': 56,
 '6f11852f-354f-4e17-93f4-03d949579d3e': 57,
 'aaf427a3-cf19-41cd-8622-e2a12731fbcd': 58,
 'd8aec8ab-0361-418a-8698-1920b452f12a': 59,
 '4ea63982-7065-4368-8f8c-a991d8567c58': 60,
 '5f22671f-9a03-4815-ac6b-787fcdbd87ff': 61,
 '7db5295a-5acc-4ae6-9bce-d7c442a2ebf5': 62,
 '26acbb32-a578-4b6d-a4b9-391503239733': 63,
 'e2e7804e-1f3d-408a-86c7-0a4b323c23f4': 64,
 '5faa3262-7d85-47ed-b90d-4b547177e90e': 65,
 '7d4041c6-0b3d-4666-b062-ee3dfb86e2c8': 66,
 '5a7cf614-1661-413a-a5fc-e24624574efa': 67,
 'c709a27f-293f-452a-9cb6-22740b4de7f5': 68,
 '26f80ecd-5026-4aa3-9be9-42733650e5ae': 69,
 'ba380294-b8f4-4e2d-88f8-1cdd75d30a7f': 70,
 '654678c5-92b3-4dc5-a088-cc15c6129c42': 71,
 '9af003f1-dca7-4b35-b794-a596b10ce4ec': 72,
 '179b1f31-a3a8-4244-8858-cb22443e21db': 73,
 '259bb4ce-fe5f-4365-a75a-f6095c9b95fe': 74,
 '42665430-860c-46a5-9c8e-b4245a7d9c9d': 75,
 'e469b8e1-fbc1-429d-8b48-f631d408a952': 76,
 '7b13a2c4-d748-4fb7-a608-30c292830fd0': 77,
 '50cbbafc-7adf-4b34-9c72-11f1e3b17391': 78,
 '2e9e3d02-3ed1-4a04-b5fd-9e867c157d33': 79,
 'fd8f517e-cf80-4fc8-9a48-b916af317343': 80,
 'da8a8527-7be0-47a1-9367-eab97905f456': 81,
 '61dee111-fc74-4510-8577-d1a12cb1add4': 82,
 '1613d371-0469-4b5f-bf99-4b48e2e0241d': 83,
 '751e56aa-c70c-4bd0-b295-db0d86448dff': 84,
 '9a18f28f-4311-424c-80d1-ee94c9f0ddf8': 85,
 '16b621af-36d2-4ab3-a2e9-34e171db9fdc': 86,
 'a675343e-a723-4a38-afc6-eca4731a653a': 87,
 '547a0b1d-10fe-487a-9f59-e6814cc72911': 88,
 '48513388-9ec6-43db-97f1-1a4e349fc40c': 89,
 '90218260-a821-4284-a7b4-ad7d60f19025': 90,
 'bc900cd5-8826-4014-9adf-9c7190b2b0a0': 91,
 'c64e846b-c86d-4b8e-ac2a-f2cd0b7392ee': 92,
 '617d211d-4097-4ce9-9e89-a65215d596f5': 93,
 '4ac9b643-7423-4008-847d-1e00ec3d39f6': 94,
 'e02dcdc8-4b34-4181-ac95-efad85b9ead7': 95,
 '52770a8c-e125-46ea-adbc-4882fb7fb28e': 96,
 '49e8d528-18b0-4a3e-a93c-af4b59b8b6bb': 97,
 'cd2bd925-71cb-4105-b0ea-60988e811d12': 98,
 '3b1dd2f1-3d97-4687-872e-789d2f4c904d': 99,
 '8785c908-f97e-444e-ab9f-622a29336bd1': 100,
 'f5669f75-cdf7-4a33-bc68-d5056cdce204': 101,
 '3a8ad294-4d39-4919-83c4-757758f573bd': 102,
 '9828a99a-e793-4655-8fad-2a582873fa7e': 103,
 '0b271719-a0bf-470d-8aa5-c62dbddde8f3': 104,
 'd873109f-30ae-4d75-af4c-746fc1703eb5': 105,
 '8865b7c3-47df-4586-afdd-fdd89adcf139': 106,
 '9999eafa-3caa-4a83-92c3-9f3acb75a848': 107,
 '3700443b-e2f0-4682-86cc-7bf44386a3e0': 108,
 'b75c5e2d-ba0d-468c-990d-f67fba958573': 109,
 'de228451-9e98-4c64-bfb5-74def35e99f0': 110,
 '4b05ffe2-d5cd-40b5-afe0-02f2f9ea5734': 111,
 'fc4a7e3a-8e4e-4ef5-b97b-50a010898932': 112,
 'e8294886-a810-4bdf-bf4f-74d6ac031146': 113,
 '799940f9-c2a2-4f32-ae6c-e186e8bf64d3': 114,
 'a23991f6-00ca-460f-be29-aae9f4523bf1': 115,
 '9363ad6a-c9b3-47fe-ad6c-c2c7a872d83f': 116,
 'f918dcfa-e0be-4f58-956e-512168e990e8': 117,
 '0f036ef9-34ea-47f1-897b-141c4e4748af': 118,
 '8dbf98a1-8563-4930-8896-9c9fe2e9369e': 119,
 '578f36ea-12d1-48e5-bd38-48c1be784c0c': 120,
 '94c09f15-2aaa-45bf-8fb7-01a62fa0a206': 121,
 'd466e812-8857-4873-9ae5-3c232c7aa8e7': 122,
 '5c36c040-af92-4f03-b617-940f1886e4e0': 123,
 'b3f34a46-11e3-4016-9413-555b92dc0487': 124,
 '7133a936-4ce7-4ac6-9aa9-4f02ca1002ba': 125,
 '1ccd3cb5-04c9-4fee-b993-94d45618a7e1': 126,
 '65f330f0-aa8e-489d-a7a1-8ed126b9d78a': 127,
 'a3d35dfb-db77-4204-8ee2-0e8a09d15b36': 128,
 '79058416-0be3-44d3-9200-6f2869306150': 129,
 '1a31dc8e-e077-4bd2-952f-68f0250b37d8': 130,
 'd1257fc4-24e1-4c74-b6da-5715c9c78730': 131,
 '664d1bee-0ec7-4b74-a85c-de5c2828ee6c': 132,
 '2810d39e-d2c8-4527-ad2b-f6746dbb4142': 133,
 '106010dd-6307-4818-aff8-b387ac8416e7': 134,
 '3bbe5281-9d7a-4c3d-9018-71fb28d8d2a9': 135,
 '89728784-0cb4-4711-be04-66e190d4ae7d': 136,
 '840eac67-4edc-461b-9848-2aa40abe03a3': 137,
 '7739e18d-0872-4053-b7da-2ea33a54760c': 138,
 '5916fc71-89cc-4c5c-8c42-3351ddc1397d': 139,
 'e56d06a1-d5f0-4cae-9655-89c8cd83ced8': 140,
 'e23422e7-646c-45fa-b6bf-91253439a6f8': 141,
 '059dbc3c-f08a-4728-8b34-a26228642f5e': 142,
 'c1f65276-60bf-448f-8f03-19024eedc401': 143,
 '35b33939-87b7-4036-87df-12e75d3d14fb': 144,
 'a990cb02-0662-4fde-b898-2f4610059745': 145,
 '8e4af023-d3af-46ce-b55d-2fcb08539fe1': 146,
 '432cb43f-c0f0-4d45-8b3f-d34f6e9fd655': 147,
 '639a4488-9d4e-4a39-8c28-b3a74e56117a': 148,
 '71264264-bbd0-4401-bb73-3a96d9ca5365': 149,
 'aa7772f2-f240-4f70-bc77-41fc4c04233c': 150,
 '7f80be1a-ed9c-4203-9b2d-4ea4c89f3fba': 151,
 'c829ed99-eda8-4a93-8c4e-84af80c4290d': 152,
 '7315896d-f504-4552-999a-fe58e2e743b6': 153,
 '480b192c-ea83-4092-8fc2-ffb8b13767b7': 154,
 '544b7a0e-9646-4652-9c07-18a71faf630c': 155,
 'fc5fd150-bf66-4b9e-94d4-55083c78de67': 156,
 '42697a0e-0f67-49f7-b549-75d2621955d7': 157,
 '6dd097e4-5d5e-4001-927b-b99f0fb59aee': 158,
 'f27958ce-fa24-42b9-8e21-4ac257d311ce': 159,
 '0f4336c6-60a9-4319-a1ae-d4a2a98ff700': 160,
 '6de913a4-2b24-434c-934d-87f293e4a56b': 161,
 'e1b05045-c239-484b-b893-f6aaff12782a': 162,
 'ce4c2708-d6ee-4ef7-8ce0-7e75e390046e': 163,
 '3c51b0be-7385-4aeb-9e41-ef8a4ee63371': 164,
 '7b7044b3-4d4f-4a0b-a165-9b1a9ef22ff2': 165,
 '9d0e045d-ab35-4020-a821-589ece87a458': 166,
 '9d80612e-d6e9-4a6f-8551-217afd713286': 167,
 '8fe8b08c-6e51-4500-917a-c901a36137c1': 168,
 'ac11eb45-b31f-4dc4-aad6-66d27bc02af8': 169,
 'a09561ad-5c98-4512-9af3-6f982c738031': 170,
 '6ba1dead-9f34-444c-9d61-35f37578c373': 171,
 'c04df90d-0dd9-4eef-8661-ad68cb625cbd': 172,
 'bcd2af9c-1a17-43e9-830a-4e6378252d9e': 173,
 '0fd6c287-196d-4181-9561-b9f2ba827f1e': 174,
 'ff55abe0-d04a-44f3-9994-40ccbe57a834': 175,
 'b73575dc-2aeb-44e1-8843-53e33247d481': 176,
 '955553d5-ebb6-4647-8c90-04ca93af4f50': 177,
 'd2e1ea29-a1ed-401d-b038-fccb7a37d956': 178,
 'a1107a6c-b09a-42bb-8b93-1e7cc6182d53': 179,
 '1769377d-1df0-4e15-ad83-246e5d10889b': 180,
 '0a60ae7c-8165-400c-9505-1b00631560db': 181,
 'aee1a123-9dc5-44e4-abe3-d72b6bc4f72b': 182,
 '5b35021e-d58d-4b0c-a762-fa9b92d37758': 183,
 'a11e51bd-d0b3-44db-bff5-6390ef5fcb30': 184,
 '75010bfb-4249-4a32-a8e4-e182a8815f8e': 185,
 'c695cda9-b513-49ae-a229-bee488ea3721': 186,
 'c457af7e-857e-4fdf-bcb7-67cec7e58f0b': 187,
 '5d41fd1a-bf76-4d1f-968d-f684d6e49311': 188,
 '2771ed8b-0798-46a4-87b3-fe9bc7b47fc5': 189,
 'a07df328-8141-4602-90e7-0ae0219d0f6d': 190,
 '4ec06392-51d4-40c0-9d0a-7c9e16d6e488': 191,
 'a85891f4-f237-4737-b6ec-590c62fab166': 192,
 '3c8ebe31-d977-46a7-b127-ab1a6dfa9c07': 193,
 '98073ec1-7d22-48ed-bf07-7910efc46d54': 194,
 'd0f8ff51-e535-4779-98e0-9904cc11f9bf': 195,
 'eda69eea-78cd-47d6-a544-025b3935802a': 196,
 'a4d68068-ffef-45d2-8035-fdaabfcf5d19': 197,
 '75db2d8b-98d7-4166-9658-53fe63155bd0': 198,
 '6c880aa1-b9b4-4999-bc73-b73b85d18336': 199,
 'c7414878-4623-4c1c-ba42-0e2fa68d9dae': 200,
 'ac177fab-d96b-4e12-8aa5-ef6062ee1f11': 201,
 '2b97ccf9-007b-4068-937c-e895adb6787b': 202,
 '932eaf80-754e-4c28-bdb8-73ef64c0841e': 203,
 'fe63d20a-4aa2-4e8a-8910-cf398ad8ccc9': 204,
 '2a1af277-f1c6-4d04-afa8-deff0d38f9a2': 205,
 'bcd14efd-dce6-4ba1-ac36-03cbd8f4e807': 206,
 '82b84832-571f-485e-92b0-fc2527b54477': 207,
 '2418b031-9c6e-4aef-ac5c-1a041a02dc4d': 208,
 '01c8f136-4ff5-4199-a8fc-45f459de755c': 209,
 '1456af8e-2ce2-471b-a110-32c8364ceebb': 210,
 '17ba504a-7f37-4b12-bf20-f0c9cf0d4072': 211,
 'abe8f37a-00e2-4a30-bda1-6fcd204bc1f0': 212,
 '246e2075-9774-4c01-be30-84b419968717': 213,
 '6f26daab-b132-4429-8db1-371204a376a8': 214,
 '358c714e-18e4-4f16-a220-59dc3d246e69': 215,
 'd0c1a126-e2e9-43e1-8f66-de9ebd4950f9': 216,
 '8f41c6f6-f866-4f17-9d97-7d3b299f1d52': 217,
 '5694efd8-fe1f-48f0-8c9d-eb7eb0ba60b2': 218,
 '020aa535-914c-4b7b-be33-b0abbf3b8830': 219,
 '5dadae84-5e00-44a0-9503-b3b158441f7e': 220,
 'd87d571f-4a2e-409c-8fd6-4c1b5a1d2abe': 221,
 'cc79c46d-50a5-413c-97f1-c9b2cefb1ebd': 222,
 '43279afd-a266-422b-ab36-10e667105c91': 223,
 '622b6e5f-5a1f-4006-b5ba-e99179166bf5': 224,
 '827f9035-58bc-4068-abfa-09f7e0a4ed7a': 225,
 '77b6091d-0ceb-4723-9e0a-5d312fa08b8e': 226,
 'fe065955-5d27-4aac-8efb-9673754b8288': 227,
 'ed5784b4-5af2-4d92-91d6-5bd4b27749f5': 228,
 '48d868e9-0950-49a1-9562-31c6e41916a3': 229,
 'eef9dd97-62e8-4076-90c0-6e00828fe219': 230,
 '3dbcb1dd-9cf7-4e5a-957f-779adf8d41e8': 231,
 '9aad24c9-8c2a-44f9-b72a-c6b5ebf0f0b1': 232,
 'c5a42f0f-1d9a-4daa-88b0-71651b271304': 233,
 '10e4a117-bac1-4682-b011-d2b8bfff08a7': 234,
 'd924f56a-3ff4-4e94-8929-94f944ccef1a': 235,
 '57b1f7a2-797a-4f2a-95d4-236836f02bd7': 236,
 'c7442825-efc4-4824-8d67-3a6a180375d1': 237,
 '3ac4c3f4-cb1b-4718-a92e-79dac8559860': 238,
 '6a4ac377-cbaa-448a-8460-037e6c144756': 239,
 '1459f628-c5a1-43b9-9d9d-c80d8c75a816': 240,
 '75e3f408-9c56-4fe1-8e28-627d7cd65478': 241,
 'd040df89-4636-40d4-be44-fa3c7fae64ae': 242,
 '461ad2d4-9ab3-4ddf-9c94-1b5df3f241fb': 243,
 '8fb4e559-8101-4aa0-9afa-729894a9018d': 244,
 'b052d836-c9b3-4b4f-9707-51e997ee8010': 245,
 '3b92f1da-e69b-48b7-957d-39759769dc23': 246,
 '4bffcf84-6256-461e-aea1-ae281a2e2603': 247,
 '8badcda4-2648-479a-9be5-f265d2d3b60e': 248,
 '3341826d-a742-4778-bd97-f355c695aaa2': 249,
 '02e28e50-01c3-4129-a64b-f17597c10390': 250,
 'af1dbb1b-56ee-45c6-936b-874143db8472': 251,
 'ba8bb363-c3e7-416c-9aa0-27e252d84f7c': 252,
 '1133075a-74f2-4496-9060-88d7fff37871': 253,
 '369ba5e3-5291-4d65-8096-0fdc034004a9': 254,
 '341a32a4-2314-49f4-a4ad-26f7d7507501': 255,
 '8f8b1ae6-3f0c-49c3-a4ab-2a8987df1a1f': 256,
 'a6dd1e59-f981-4a0b-9049-4a864be5b9d2': 257,
 '3c5ea65f-259e-453e-8360-614cc9932814': 258,
 'e29d5f69-68a9-49db-ae32-9234fab2079f': 259,
 '76a21a46-9e19-43e4-83ec-a69a00d96860': 260,
 '81804ad3-d148-4b17-af32-f94979f3a85e': 261,
 '32d78fbd-3967-47c8-900e-d51a17b640d5': 262,
 'd1028bb0-907f-4ccb-b23c-9ddca2abe5ee': 263,
 '44bb8833-b5ec-462b-ac3b-97587459cb1b': 264,
 '3bf65784-dd7b-46f2-b17d-1f8787740a11': 265,
 '2b2de752-d654-4ef6-a9bb-1c242de6f40d': 266,
 'f92f361c-9ef8-4dc4-aa15-68b70fd26178': 267,
 '2669e2ba-770c-4394-9c1b-f6f508176f27': 268,
 'd932c34a-e4ce-4453-a782-93090b5dc2da': 269,
 '390b7219-5290-4d4b-ac2d-6667dec8b417': 270,
 '5e2ee1a3-e838-42ed-837e-11136b43061e': 271,
 'cfd17df5-e1c1-4798-927c-6140cd851bf9': 272,
 'f9693deb-0df5-43e0-b0d2-ad5ea6a675df': 273,
 '412a0b31-e7d9-4bc2-bf9d-7497738719a9': 274,
 'e676d8e0-9d65-4ba7-8a22-f1b79d0fede3': 275,
 'a86aef90-7102-48ee-b335-e08678224bbe': 276,
 'd0f90a9d-b51a-4df3-a26f-4f91c9e061d0': 277,
 '9813ebb0-c58d-408d-a57c-a08743a660eb': 278,
 '3df6c1ae-0c25-44dd-a954-eeaa96970b14': 279,
 '32348900-1fe0-49fa-a4cc-01e434a36be2': 280,
 'ff9f37f4-a66d-4198-95b9-4554a74521eb': 281,
 'a9be5ca9-0523-4ea2-876c-1261bb36e77d': 282,
 '8d178071-0640-4580-9d46-e4a468c5402e': 283,
 '3c0a7998-0c1b-4d8b-a919-a466dab99ccf': 284,
 '537c7760-10cf-41b5-bf91-acd85bc2a664': 285,
 '5eb59a5b-039a-43d3-9e69-4eba9e568057': 286,
 'ffa8a291-a68b-4dc4-908d-3e3ac5ce80bf': 287,
 '8aaadc95-a4c0-4535-9744-d8f96c5b1b5f': 288,
 '313d4aa8-f865-4246-899b-ee685efefaef': 289,
 'eede80c5-e69b-4bc7-a217-fa17f227f110': 290,
 '32879479-af9f-4c70-a4dc-11b4169c64ef': 291,
 '449b9dad-8fa7-4b4c-81c3-9e909326b56c': 292,
 '0e92bab4-ebee-4784-931c-2b318498e533': 293,
 '0f69f484-08f1-4001-8d31-e9c800f823b4': 294,
 '55bd7b7d-5af9-45f7-9ba7-44de6fe1e19f': 295,
 '440b5643-878b-4cca-92db-2b4c4157ab03': 296,
 '04893d88-4c11-442e-8b27-67c545b0e9fe': 297,
 'd5219930-dcf3-4302-a64d-80898fd6cf6f': 298,
 'edc1a71d-3fc5-4e77-ad96-bada5d358b1a': 299,
 'cb279884-b7e5-46df-9fdb-c35f7e2002aa': 300,
 'ca20716b-b012-40fc-bfd8-7d333c0e2b10': 301,
 'e4032928-9ede-4b48-8836-8a09ba6e8ea1': 302,
 'cdb44f6a-787d-4195-9a6c-01405ef1dfff': 303,
 'e7931336-a52a-48bd-92d2-292acd5bdeca': 304,
 'bb6f367b-1eba-44b7-9aac-eba5b47075f6': 305,
 '76660a82-5e75-4306-ab51-9d37bf3f91fd': 306,
 '3b51b54b-0a19-4b0e-8ace-0df3238163f0': 307,
 '06cf61b6-fd05-4a32-bbfd-21dbf9ef4bb8': 308,
 'd4bda562-ab28-44ba-865f-2562829ede02': 309,
 '51d1cec3-1d97-4383-b793-c6fdd851770a': 310,
 '77f3d005-970a-4e2e-96e8-ccaeabd6cb4a': 311,
 '4ec51e68-6da9-4bbf-90a6-1f7083f00c72': 312,
 '255706fe-02d6-4437-91b5-794e8d8537ce': 313,
 'f148fbd3-23ca-4802-b6b0-0075193160ad': 314,
 '841bfeed-2081-4797-b6a0-1087aa7c2846': 315,
 '226846f5-1dca-4e84-920e-7145e2e2674c': 316,
 '5295127c-660a-4e5d-a80a-637cf2538cf1': 317,
 'fb6a300a-d762-43b9-b36c-4b290d321cb3': 318,
 'dfb63c86-b6a0-4472-b3a1-a678c5849852': 319,
 '222a9261-4aa1-46da-b070-7bff29f9a71f': 320,
 '34b65b72-9e7c-4d43-9d65-b649be22ea48': 321,
 '065e887b-1c5e-4994-a6d1-476c006c13c1': 322,
 'd966689c-5ada-44e5-8783-20fb5770bae9': 323,
 'aac093e2-efa3-462f-ad62-70820edfeb71': 324,
 'b1cceae9-5958-4220-9e5b-ed0203465792': 325,
 'ad1edf31-6c23-4787-b2bd-2142ffcf9ae3': 326,
 'f1e985f7-3076-4f83-8dea-dcb0b2720c1f': 327,
 '9f413689-4784-47fd-8c36-d33d9aff1cfa': 328,
 '18a94169-a570-458f-a138-cd093d221152': 329,
 '386e07d3-abf8-408a-9543-fcf21aa5914c': 330,
 'f21a4eec-8f05-4732-a632-a8476b9cb29e': 331,
 '0c74b7da-781f-4ac2-8c37-859476b8f15f': 332,
 '8c255591-b500-4f4c-b9e1-aa2fa3b90d71': 333,
 'e1233187-a521-4488-bde6-a35d33b24ae8': 334,
 '9e6c38f0-df4c-4f23-b451-989ba4e4a108': 335,
 'd6c12f61-dd09-42b6-931c-13e9da8e5012': 336,
 '94e56943-7125-420e-bc6f-0ed5394f13e7': 337,
 '4d449fff-83c6-4ea6-9e0e-d38129e6c530': 338,
 '2d9d4514-0b9c-419b-8b8f-ff060fbcccab': 339,
 '52b680f6-5cfe-4824-8f65-46cc4c56c958': 340,
 '959a1c8c-eed3-4bce-ad5c-e43db0b2615b': 341,
 'de882c5a-725a-4a50-bf39-480980c2d8a1': 342,
 '3154dab0-f364-4a37-9c79-91e5d53f40ba': 343,
 '7282ee7f-40cd-4a9b-89ff-cba19619d030': 344,
 '66fe5bc0-3e06-42bd-a00c-0e4bbfa01fbe': 345,
 '2c0f9bd5-c111-452e-a2ac-955b832310c4': 346,
 'e36a5894-0d0c-412b-9fff-2025795a8c38': 347,
 '5ae3be43-838e-489a-a7d2-d413eca86ef6': 348,
 '033053eb-62bf-4a93-a6ab-d34494b13c61': 349,
 '4ecd920c-3343-4d6a-8fba-02451880509e': 350,
 '0c0690dd-ba86-4c53-b2da-2ba2a913f1ed': 351,
 '59a29e50-2127-48d0-b177-0078a0a188b8': 352,
 '2343b31d-1a4b-4b20-b4d9-6e76928f1cc6': 353,
 '1dabea69-d74a-459c-af88-d1905c5e665a': 354,
 '7dd488dc-1c9b-431d-bf68-9f93b78b0415': 355,
 '4c3a46ec-1fea-4519-a43b-478d5f2d179d': 356,
 'd4fc0dcf-ed43-42aa-8b29-7e6e99572a92': 357,
 'aae6162c-19e3-4d0f-b28c-2c8e6a26269d': 358,
 'c94452bd-22e9-42a2-a788-24c8c17e242f': 359,
 'c8761341-fda8-412b-8c22-e35573ae7cf1': 360,
 '5ae3adbc-cef4-4335-94eb-d8e2acbc1d37': 361,
 '8704f267-56ef-463b-89ef-123f2f9ff449': 362,
 '51a0441f-4517-422e-8930-8dfad273b1c1': 363,
 '102e80ee-2bf9-43eb-ac0e-3ff29c4a89f7': 364,
 '42faf089-ab1b-4414-bef2-8887564d9474': 365,
 '3b50f561-694e-43ad-8055-f6a14b97c47d': 366,
 '78e65ab9-c2ac-4a6b-9adc-5d0098f1156d': 367,
 '69f3f5ad-da7b-497c-a40f-32bf825d9c78': 368,
 'e54a017c-3c0a-46a6-ac90-5e3213eca4bc': 369,
 'c76e5b19-d728-4de4-b9a9-5c8fd98bf139': 370,
 '08223347-40a1-460b-8928-2587ef776bcb': 371,
 '0ba9d0ba-1c3b-425b-bf22-b08f8a83ab1d': 372,
 '55856fad-e5e6-4a64-aca1-066383a45e4e': 373,
 '6b7ebbd5-db85-4213-a35e-a928dd97fcb3': 374,
 '9ab93842-0da4-4ddf-acfd-4f9f95735d15': 375,
 '7c6d1fc3-8099-4b1a-9573-3e3944d70a2e': 376,
 '1e5c900e-d2c6-4fe0-98e0-1399ffd9db35': 377,
 '4700f517-5c5d-483c-81b7-d77aca04991c': 378,
 '885bbf8e-90af-4728-be30-7bc2749e96ae': 379,
 '96cfe8a4-7e1c-49d4-ba42-fd42fea99131': 380,
 '9eb23847-4a7e-4917-8200-346c96a81fb5': 381,
 'cfa24888-51eb-40dd-aeee-b35c527d5d75': 382,
 'e0444f25-9664-450a-abe8-f64bbc879e68': 383,
 '52828aa1-3261-41e1-9069-b758fd5694b8': 384,
 '03be4402-d4ad-482f-8fba-2bbd3e0a5120': 385,
 '8c6cbb3d-4679-47bd-8246-a68fd49e8332': 386,
 '0827c64f-91b5-4761-a56d-25b7747fa9e5': 387,
 '4b63f339-9fdb-44a5-9097-0ed784a3a6ef': 388,
 'ba3aa215-5eb0-4ab8-8dea-eb2373f84a41': 389,
 '04d6105a-ee00-4e1c-a3d1-bf93fa868d80': 390,
 '60cce1e2-515c-4b00-b513-1b06b0d2bed1': 391,
 '40a68f41-a326-4527-9447-c7e696564500': 392,
 '3289e320-e963-4cc0-9e4b-009407e94ac9': 393,
 '45e89989-b3fe-4380-a260-49ab170c93f8': 394,
 '0fbb5951-9413-4a04-8a07-be6b9f1c094d': 395,
 '666b7ed6-bc75-4343-99cc-fa5c894bbb02': 396,
 '2d02962a-7705-40e3-b5dd-e3217995c239': 397,
 '923de7c5-c1ce-4325-ae52-12d6c05cae0e': 398,
 'bd6df4f1-2857-4e49-92e7-e0508b8b6e14': 399,
 '34d4b456-fb9e-4ecc-a7cf-ec577e05b950': 400,
 '74fe3ca4-21f7-4767-aa4a-e041368bd94f': 401,
 '8d8d59c3-8396-4b61-a6af-2692c1daeedf': 402,
 '85814d0a-c5ae-425d-89fc-696762c18b4a': 403,
 '9ba7d001-fa75-4503-bf42-a657fb2ea51f': 404,
 'cf15fcf3-9c3e-4af4-8149-14362fd056de': 405,
 '74235a12-97c5-4d3d-9db2-f2789b3c12fc': 406,
 '2a3f866a-bac1-48e2-b86f-fbfc9edd1dad': 407,
 'c482054a-5484-406b-8f70-d9a9e29230b0': 408,
 'a0b2a415-5137-40f1-851d-daff3a967e8c': 409,
 '870c8a9a-9977-43e1-a62d-cebc38d181fe': 410,
 '29b85573-78d2-4272-84c7-be946450a1ae': 411,
 '4befe1d6-d7dd-4782-b88f-7862e9029e36': 412,
 '2f29c0fb-7499-4929-ba90-b9cd046b1dc8': 413,
 'c1d34f12-d977-43b1-8799-b4c31d645b0b': 414,
 '4b4311d8-dc28-45b8-b2a8-b7b28e338407': 415,
 '85ed3198-6892-47ba-9919-322ce575f758': 416,
 'ea4f0131-0afd-42c1-8365-57c6271fcde3': 417,
 'caf73a61-086f-4d8d-8d2b-fb608e1fded4': 418,
 'fd3df731-a0d2-4e6a-9c97-9a6629c05cef': 419,
 '1d5e11fc-9f9b-4e84-bb59-77b8ad1bc9c7': 420,
 '33b9f9e8-639b-4aea-bed5-d550384614d5': 421,
 '8385406d-9d76-46ae-93d8-c89e8a6239f8': 422,
 'f42e9fae-937e-4231-91c1-1a2dd2e38d0e': 423,
 '42c44c1c-54ed-4d21-b32e-f163c7dcc4f8': 424,
 'e2a4321b-8de8-43ea-bdbf-024695e08563': 425,
 '3aa6d1f5-11c3-465e-a50f-da20708e4281': 426,
 '289c0c12-c787-49a3-b015-b2c11a5df94f': 427,
 '1d227206-370b-4bd1-986b-6a9572e365a3': 428,
 'b89b6e68-7d23-4c2c-89d2-ec96f3e82e5d': 429,
 'de22bba9-a2a9-4e23-9ccf-162effd7a543': 430,
 'c7051969-d7f7-4e6e-bc0c-010cc4d212c7': 431,
 'b83b839e-0501-41f5-a33a-27cef8f9dfa8': 432,
 'c21e72dc-c914-4058-911d-27efde0339de': 433,
 '842afa31-b3b5-4d19-a16b-049d2a1b5345': 434,
 '2d5ce9bd-5a89-4e10-879d-932061aeba91': 435,
 'a892794b-58bb-4f72-9722-d2316cdd0ff3': 436,

In [10]:
doc_indices["13db0ab1-eea2-4603-84c4-f40a876c7400"]

0

In [42]:
def recommend_news(user_history, top_n=5):
    if not user_history:  # Cold start (usuário novo)
        return df_items[df_items['page'].isin(popular_articles[:top_n])][['page', 'title']]
    
    # Obter índices das notícias que o usuário viu
    viewed_indices = [doc_indices[page] for page in user_history if page in doc_indices]
    if not viewed_indices:
        return df_items[df_items['page'].isin(popular_articles[:top_n])][['page', 'title']]
    
    # Calcular similaridade entre as notícias vistas e todas as outras
    user_profile = np.mean(tfidf_matrix[viewed_indices], axis=0)
    scores = cosine_similarity(user_profile, tfidf_matrix).flatten()
    
    # Obter as top-N notícias mais similares que o usuário ainda não viu
    recommended_indices = np.argsort(scores)[::-1]
    recommended_pages = [df_items.iloc[i]['page'] for i in recommended_indices if df_items.iloc[i]['page'] not in user_history]
    history_pages = [df_items.iloc[i]['page'] for i in viewed_indices if df_items.iloc[i]['page'] not in user_history]
    return (df_items[df_items['page'].isin(recommended_pages[:top_n])][['page', 'title']] ,df_items[df_items['page'].isin(history_pages[:top_n])][['page', 'title']])

# Testar com um usuário aleatório
sample_user_history = df_train.iloc[0]['history'].split(", ")
sample_user_history

['c8aab885-433d-4e46-8066-479f40ba7fb2',
 '68d2039c-c9aa-456c-ac33-9b2e8677fba7',
 '13e423ce-1d69-4c78-bc18-e8c8f7271964']

In [43]:
recommendations = recommen_news(sample_user_history, top_n=5)
recommendations

,page,title
15859,f0a78e58-ec7e-494c-9462-fbd6446a9a89,Caso Bárbara: suspeito de envolvimento no assa...
23198,d2593c3d-2347-40d9-948c-b6065e8459a9,Anestesista é preso em flagrante por estupro d...
26314,6a83890a-d9e9-4f6b-a6c6-90d031785bbf,Pizzaria recebe PIX falso e entrega refrigeran...
60121,1f32787b-de2b-49be-8c20-ddaeae34cc22,Filha é presa por golpe estimado em R$ 725 mil...
71660,f6b5d170-48b9-4f8e-88d4-c84b6668f3bd,Diretor da Caixa Econômica Federal é encontrad...

In [13]:
import pickle
import joblib

# Salvar TF-IDF Vectorizer
with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

# Salvar Matriz TF-IDF
joblib.dump(tfidf_matrix, "tfidf_matrix.pkl")

# Salvar Dicionário de Índices
with open("doc_indices.pkl", "wb") as f:
    pickle.dump(doc_indices, f)